services:
  postgres:
    image: postgres:17
    container_name: uber-lite-postgres
    environment:
      POSTGRES_DB: uber
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-test:
    image: postgres:17
    container_name: uber-lite-postgres-test
    environment:
      POSTGRES_DB: uber_lite_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: uber-lite-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: uber-lite-mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8025" ]
      interval: 5s
      timeout: 3s
      retries: 10

  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: uber-lite-buggregator
    ports:
      - "8001:8000" # Web UI
      - "1026:1025" # SMTP
      - "9912:9912" # Var Dumper
      - "9913:9913" # Monolog
      - "10001:10001" # Ray
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8000" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
  pgdata_test:
