services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: uber-lite-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rustfs:
        condition: service_healthy
    volumes:
      - .:/var/www
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: uber-lite-postgres
    environment:
      POSTGRES_DB: uber
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-test:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    container_name: uber-lite-postgres-test
    environment:
      APP_ENV: testing
      POSTGRES_DB: uber_lite_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: uber-lite-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: uber-lite-mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8025" ]
      interval: 5s
      timeout: 3s
      retries: 10

  buggregator:
    image: ghcr.io/buggregator/server:latest
    container_name: uber-lite-buggregator
    ports:
      - "8001:8000" # Web UI
      - "1026:1025" # SMTP
      - "9912:9912" # Var Dumper
      - "9913:9913" # Monolog
      - "10001:10001" # Ray
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8000" ]
      interval: 5s
      timeout: 3s
      retries: 10

  centrifugo:
    build:
      context: ./docker/centrifugo
      dockerfile: Dockerfile
    container_name: uber-lite-centrifugo
    ports:
      - "8000:8000"
      - "10000:10000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 10
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  rustfs:
    image: rustfs/rustfs:latest
    container_name: uber-lite-rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
    volumes:
      - rustfs_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9000" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "10001:10001"

volumes:
  pgdata:
  rustfs_data:
  pgdata_test:
